### ISSUE TITLE
Could not find `interpolate` in `dasp`

### ISSUE THREAD

**Issue by chaosprint** [RustAudio/dasp#126]
also I try dasp_interpolate, and i got

use dasp_interpolate::linear::Linear;
  |                       ^^^^^^ could not find `linear` in `dasp_interpolate`

**Comment by mitchmindtree** [comment]
Be sure to read the updated documentation on enabling the necessary features:

- dasp - https://docs.rs/dasp/latest/dasp/#optional-features
- dasp_interpolate - https://docs.rs/dasp_interpolate/latest/dasp_interpolate/#optional-features
