### ISSUE TITLE
Incorrect feature name for `window` in `dasp`

### ISSUE THREAD

**Issue by linclelinkpart5** [RustAudio/dasp#150]
It looks like the `signal` feature flag is being used accidentally instead of the correct `window` flag on this line: https://github.com/RustAudio/dasp/blob/39015e639118d281d660dfb5dd1bc26365318f46/dasp/src/lib.rs#L133-L135

**Comment by jdanford** [comment]
@mitchmindtree – looks like this can finally be closed

**Comment by mitchmindtree** [comment]
Closed via #142.
