### ISSUE TITLE
Add a way to reset interpolator

### ISSUE THREAD

**Issue by vaffeine** [RustAudio/dasp#162]
I am using `dasp_interpolate` crate, and it works really well.

However, I need a way to reset an interpolator. Simple interpolators (like `Linear` and `Floor`) are cheap to re-created, but `Sinc` needs a new buffer, so it is not optimal to create a new buffer in order to reset it.

JUCE, for example, supports it through the [reset](https://docs.juce.com/develop/classGenericInterpolator.html#a44d513d729c6dd222d496fcf73bc7818) method.

I would love to open a PR that adds the `reset` method to the `Interpolator` trait if it is something that is desired.

**Comment by mitchmindtree** [comment]
@vaffeine thanks for the issue, I think a `reset` method makes a lot of sense and I'd be happy to see it added!
